name 'artemis'
maintainer 'Shaw Innes'
maintainer_email 'shaw@immortal.net.au'
license 'All Rights Reserved'
description 'Installs/Configures artemis'
long_description 'Installs/Configures artemis'
version '0.1.0'
chef_version '>= 12.1' if respond_to?(:chef_version)
issues_url 'https://github.com/ShawInnes/artemis/issues'
source_url 'https://github.com/ShawInnes/artemis'
